package uk.ac.ebi.fgpt.conan.lsf;

/**
 * An event that is generated by an {@link LSFProcessListener} whenever the file it is listening to changes.
 *
 * @author Tony Burdett
 * @date 01-Nov-2010
 */
public class LSFProcessEvent {
    private String[] newOutput;
    private long lastOutputTime;
    private int exitValue;

    public LSFProcessEvent(String[] newOutput, long lastOutputTime) {
        this.newOutput = newOutput;
        this.lastOutputTime = lastOutputTime;
    }

    public LSFProcessEvent(String[] newOutput, long lastOutputTime, int exitValue) {
        this.newOutput = newOutput;
        this.lastOutputTime = lastOutputTime;
        this.exitValue = exitValue;
    }

    public String[] getNewOutput() {
        return newOutput;
    }

    public long getLastOutputTime() {
        return lastOutputTime;
    }

    public int getExitValue() {
        return exitValue;
    }
}
