package uk.ac.ebi.fgpt.conan.ae.restapi;

/**
 * An event that is generated by an {@link RESTAPIProcessListener}
 * whenever the job it is listening to changes.
 *
 * @author Natalja Kurbatova
 * @date 23-05-2011
 */
public class RESTAPIProcessEvent {
    private String restApiResponse;
    private long requestTime;

  public RESTAPIProcessEvent(String restApiResponse, long requestTime) {
    this.restApiResponse = restApiResponse;
    this.requestTime = requestTime;
  }

  public String getRestApiResponse() {
    return restApiResponse;
  }

  public long getRequestTime() {
    return requestTime;
  }
}
